# Generated by Django 4.1.5 on 2023-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="eligible_models",
            field=models.ManyToManyField(
                related_name="eligible_models", to="core.vehicle"
            ),
        ),
    ]
