# Generated by Django 4.1.5 on 2023-02-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_part_eligible_models"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part", old_name="common_name", new_name="sub_category",
        ),
    ]
