# Generated by Django 4.1.5 on 2023-02-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_common_name_part_sub_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="vehicle", name="year",),
        migrations.AlterField(
            model_name="part",
            name="eligible_models",
            field=models.ManyToManyField(
                blank=True, related_name="eligible_models", to="core.vehicle"
            ),
        ),
    ]
