# Generated by Django 4.1.5 on 2023-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_eligible_models_part_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=20)),
                ("order_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("order_status", models.CharField(max_length=50)),
                ("order_total", models.FloatField()),
                ("city", models.CharField(max_length=30)),
            ],
        ),
    ]
